# Generated by Django 4.1.2 on 2022-10-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_pos', models.CharField(max_length=30)),
                ('inform', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
    ]
